### PR TITLE
Added logo and error resolved

### LINKED ISSUE #223: [Style] Add logo on navbar
### What's the style idea?

We need to improve:
a relevant logo can be added at top left corner of the navbar
image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Ishita928**
# Fixes Issue🛠️

Closes #223

# Description👨‍💻 

logo is added properly and play button is also working

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷
image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
image

1. Logo should be on extreme left.
2. I am unable to select any edible, pls fix @Ishita928

**Comment by Ishita928** [comment]
I think the second problem of not able to select any edible is also coming in real application as well, pls check

**Comment by Rakesh9100** [comment]
Thanks for pointing out the issue, it is fixed now!! @Ishita928

**Comment by Rakesh9100** [comment]
Thanks for pointing out the issue, it is fixed now!!

Pls work on the first mentioned change @Ishita928

**Comment by Rakesh9100** [comment]
Are you working @Ishita928

**Pull request closed without merging**
