### PR TITLE
Issue #29

### LINKED ISSUE #29: A scroll down should be added
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

i want to add a scroll down 

### Screenshots

at this time i have no screenshot

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by ritika728**
# Fixes Issue🛠️

Closes #29 

# Description👨‍💻 
I have added two more edible items section (snacks & sweets) and also implemented the smooth scroll.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Video📷

https://user-images.githubusercontent.com/91181981/222984589-1081500d-0832-42ec-820c-35d6c77f91b5.mp4

@Rakesh9100 kindly review

### CODE REVIEW

**Comment by Rakesh9100** [comment]
I suppose you have commented the preloader, and it is removed. Pls rectify this @ritika728

**Comment by Rakesh9100** [comment]
I suppose you have commented the preloader, and it is removed. Pls rectify this @ritika728

**Comment by ritika728** [comment]
Oh yes, I forgot to uncomment, just a minute

**Comment by ritika728** [comment]
And @Rakesh9100 it actually took quite a lot of time and effort to download and edit all the images, so if you can consider upgrading the tag, that would be great! 😅

**Comment by Rakesh9100** [comment]
Don't worry about the label tag. It will definitely be upgraded or degraded as per the work @ritika728

**Comment by Rakesh9100** [comment]
image

Check this out. Use Ctrl+Shift+i to inspect and check in all screen sizes. There is too much space above after your changes. Correct it.

**Comment by ritika728** [comment]
Done @Rakesh9100, also the class 'container' was overlapping over the vertical scrollbar on small screens, have adjusted that along with this. Kindly review

**Comment by Rakesh9100** [comment]
Nice, Good work. Congrats on getting your PR merged to this repo 🎉🎉 @ritika728

**Comment by ritika728** [comment]
Thank you! 😊

**Pull request merged**
