### PR TITLE
No. of bombs increased with the time

### PR DESCRIPTION
**Pull request by Kapileswar-Moharana**
Issue Title: Adjust The No Of Bomb With Icon
Issue no: #173 

Close: #173    

## Checklist:
- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy-to-understand README.md
- [x] Update The JavaScript Code To Balance The Bomb With Edible Icon

## Pull Request Description:

I Have updated the JavaScript Code To balance The Bomb With the Icon. The WebSite According To The Project And Test It For Different Devices As It Works Well.

## Changes Made:

- Provided explanations for each section.
- Detailed Description:
- Update The JavaScript Codde To Balance The Bomb With The Icon

## Screenshots

Screenshot 2024-01-07 013322

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Which favicon you are talking about that you have added @Kapileswar-Moharana

**Comment by Kapileswar-Moharana** [comment]
> Which favicon you are talking about that you have added @Kapileswar-Moharana

@Rakesh9100 Arey Sorry Actually Dushree PR par Bhi thhodaa kamm Kr rahaa thaa Usi kaa Templatee paste karkee Chnges Kiyaa galtii see deletee karnaa uss line ko bhul gayaa hogaa...

**Comment by Rakesh9100** [comment]
Update the PR description accordingly @Kapileswar-Moharana

**Comment by Kapileswar-Moharana** [comment]
> Update the PR description accordingly @Kapileswar-Moharana

@Rakesh9100 Done You May Check Now...

**Comment by Rakesh9100** [comment]
Good, Merged!! 🎉 @Kapileswar-Moharana

**Pull request merged**
