### PR TITLE
Improved Overall Page Responsiveness

### PR DESCRIPTION
**Pull request by TuhinBanerjee31**
# Fixes Issue🛠️

Closes #

# Description👨‍💻 

Improved the Footer UI. Added Social links.

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷
Screenshot (15)

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Don't add the social icons, it's capturing and making the game screen too small. @TuhinBanerjee31 Just try to enhance the existing footer.

**Comment by TuhinBanerjee31** [comment]
I know it's taking extra space and overlapping the footer section, but can't we just set the game area till the start of the footer so that it won't overlap ?

**Comment by Rakesh9100** [comment]
> I know it's taking extra space and overlapping the footer section, but can't we just set the game area till the start of the footer so that it won't overlap ?

Yes we can, I am about to open the same issue in a few days but if you want to implement this feature, then you can. The level of this issue can be then increased.

**Comment by TuhinBanerjee31** [comment]
So, will u merge it and after that, I will create another issue regarding the game container and u can assign it to me then ?

**Comment by Rakesh9100** [comment]
It's better to do it in this same issue and make changes properly and open a new PR. It's better to have one medium tagged PR instead of two Easy level PR. @TuhinBanerjee31

**Comment by TuhinBanerjee31** [comment]
Okay. will be following that only. Thank you for your suggestion

**Comment by TuhinBanerjee31** [comment]
Made my recent updates to the branch. Kindly review it @Rakesh9100 .

**Comment by Rakesh9100** [comment]
Nice work!! Congrats on getting your PR merged 🎉 @TuhinBanerjee31

**Comment by TuhinBanerjee31** [comment]
Thank You.

**Pull request merged**
