### PR TITLE
changing the UI of the homepage(JWOC)

### PR DESCRIPTION
**Pull request by taniaban2712**
# Fixes Issue🛠️

Closes #31

# Description👨‍💻 

I made few changes, such as add neon background lights and auto typing css style.

image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Can you pls attach a screen recording of the changes since it seems that the text is not in the center of the page @taniaban2712

**Comment by taniaban2712** [comment]
I had made the neon lights more frequent near the left and less on the right as there is text on the right side of the screen. otherwise more frequent neon lights would have obscured the text. it would look bad.

**Comment by taniaban2712** [comment]
i am uploading the ui of the front page.(screen recording).

https://user-images.githubusercontent.com/110692684/219081493-b37bd9b3-4c62-4b11-86ad-b789675b14ba.mp4

**Comment by Rakesh9100** [comment]
No, the text and button should be in middle and background should be fully covered. And one more thing that when we play the game and if in between we press Ctrl+R to refresh the page then the error is there on the page which was not before. So pls see to this @taniaban2712

**Comment by Rakesh9100** [comment]
No status, so closing the PR.

**Pull request closed without merging**
