### PR TITLE
made changes for the UI 

### PR DESCRIPTION
**Pull request by Code1705**
# Fixes Issue🛠️

Closes #

# Description👨‍💻 

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷

### CODE REVIEW

**Comment by Rakesh9100** [comment]
https://deploy-preview-85--click-the-edible-game.netlify.app/
Check this out, your code is having full error.

**Comment by Code1705** [comment]
the website is not opening in my laptop.

**Comment by Rakesh9100** [comment]
It's not possible, check your internet connection.

**Comment by Rakesh9100** [comment]
See your index.html local file changes you have made instead of this site

**Pull request closed without merging**
