### PR TITLE
Add local installation guide video

### LINKED ISSUE #228: [Docs] Add Project Local Installation Video to README
### Category of documentation update

Contributor onboarding could be improved by providing a visual guide on how to install the project locally. Adding a video demonstration will help newcomers understand the setup process more effectively.

### Describe the change you think might work

Proposed Content:
A short video covering the following:

Cloning the repository.
Installing dependencies.
Configuring any necessary settings.
Running the project locally.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by rahat2134**
# Fixes Issue : #228 
Closes #228 

# Description👨‍💻 
Add a video that helps the contributor in local installation of project.

# Type of change📄

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added demonstration in the form of GIF/video file
- [X] I am an Open Source Contributor

# Screenshots/GIF📷
image

### CODE REVIEW

**Comment by rahat2134** [comment]
@Rakesh9100 PTAL.

**Comment by Rakesh9100** [comment]
Can you upload the video in Readme insted of drive link @rahat2134

**Comment by rahat2134** [comment]
@Rakesh9100 hmm, i can do that. But i thought it would be better. 
I will update it. 
Thank you.

**Comment by rahat2134** [comment]
> Can you upload the video in Readme instead of drive link @rahat2134

@Rakesh9100 i tried adding but its saying limitation of 10mb so i think it would be better if i add link.

**Comment by Rakesh9100** [comment]
Try compressing a bit to make it under 10MB without losing the quality @rahat2134

**Comment by rahat2134** [comment]
@Rakesh9100 done.

**Comment by Rakesh9100** [comment]
If done, then remove the drive link and upload the video directly @rahat2134

**Comment by rahat2134** [comment]
@Rakesh9100 i have removed the drive link and also uploaded the video directly. but don't know why its yet a type of link is visible.

**Pull request closed without merging**
