### PR TITLE
instructions updated

### PR DESCRIPTION
**Pull request by khushimarothi**
# Fixes Issue🛠️

#101 

Closes #

# Description👨‍💻 

Improved the look of instruction page in desktop as well as mobile view.
# Type of change📄

- [x] Bug fix (non-breaking change which fixes an issue)

# How this has been tested✅

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

Screenshot (41)
Screenshot (42)

### CODE REVIEW

**Comment by Rakesh9100** [comment]
You have mentioned in the issue to add illustrations to make the box beautiful and designed. @khushimarothi

**Comment by khushimarothi** [comment]
I  just adjusted the gaps and update the size of the headings so they looked uniformed. I thought illustration  will make it look too filled. Adding it now. Will ask for a review.

**Comment by khushimarothi** [comment]
Screenshot (45)
in responsive, I set the image display to none 
Screenshot (46)

**Comment by Rakesh9100** [comment]
I suppose it's fine and good-looking without this picture. So pls remove it. @khushimarothi

**Comment by khushimarothi** [comment]
See Told You . alright no issues.fixing it

**Comment by Rakesh9100** [comment]
Good!

**Pull request merged**
