### PR TITLE
Difficulty Mode Added

### LINKED ISSUE #244: [Feature] Easy/Medium/Hard Level Selection
### Description

I would like to add a new feature to the game. Players should have the option to choose between three difficulty levels, easy, medium, and hard, before they start playing.

 This option should be available after they have selected the food they want to play with.

 In the easy level, the number of bombs and rotten ingredients will be less, and as the difficulty level increases, the number of bombs and rotten ingredients will increase accordingly.

### Screenshots

Level selection options will be given in this page only.

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Surajit0573**
# Fixes Issue🛠️
Closes #244 

# Description👨‍💻 

I added the options to choose between three difficulty levels, easy, medium, and hard, before they start playing.

After selecting the modes its control the number of bombs, time gap between edible and rotten element and probability of showing bombs and rotten elements.

image

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

# How this has been tested✅
I tested this feature in my local system, and it is working perfectly.

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added demonstration in the form of GIF/video file
- [X] I am an Open Source Contributor

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls resolve the conflicts @Surajit0573

**Comment by Surajit0573** [comment]
@Rakesh9100 All conflicts resolved.

**Comment by Rakesh9100** [comment]
Why are you closing this @Surajit0573

**Comment by Surajit0573** [comment]
> Can I know why are you closing this PR @Surajit0573

I will create another new PR. I mistakenly delete some important code to resolve conflicts but now game is not properly.

**Comment by Rakesh9100** [comment]
Can the error not be resolved in this PR only, if you can't then go for the another PR @Surajit0573

**Comment by Surajit0573** [comment]
> Can the error not be resolved in this PR only, if you can't then go for the another PR @Surajit0573

Hi @Rakesh9100 , Sorry I couldn't resolve the error in this pr only, I created another PR #252 , please check that out!!

**Pull request closed without merging**
