### PR TITLE
Feature Enhancement: Customizable GamePlay Time Duration

### LINKED ISSUE #132: Enhancement: Allow Custom GamePlay Time Durations
## Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Feature Enhancement @ SloP 3.0
I've made an enhancement to the "Choose GamePlay Time" feature in the "Click The Edible Game" game. Currently, the game offers predefined time slots of 30 seconds, 1 minute, 1.5 minutes, and 2 minutes. I've modified the code to allow users to select a custom time duration between 30 seconds and 5 minutes, providing a more flexible gaming experience.

### Proposed Changes
- [x] Update the "Choose GamePlay Time" section to include a time range slider that allows users to select any time duration between 30 seconds and 5 minutes.
- [x] Update the game logic so that the user can play as long as their desired duration seamlessly.
- [x] Update the UI to maintain repsonsiveness of the game.

### Motivation
This change enhances the user experience by giving players more control over their game duration. It can make the game more engaging and suitable for a wider range of players who may prefer different time limits.

### Additional Notes
Please review this enhancement request, and if it aligns with the project's goals and standards, I'd be happy to create a pull request to implement these changes. Your feedback and guidance are highly appreciated.

## Screenshots

gameplaytime-box-change

## Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by SoumyadevSaha**
# Fixes Issue🛠️

Closes #132 

# Description👨‍💻 

## Aplied Changes

1. **Customizable GamePlay Time**: I have modified the "Choose GamePlay Time" section to allow users to select any time duration between 30 seconds and 5 minutes. This enhancement provides users with more flexibility in choosing their preferred game duration.

2. **Updated Game Logic**: To accommodate the change in customizable time duration, I have updated the game logic (main.js under assets/) to ensure that the selected time is reflected accurately in the gameplay. This includes adjusting time tracking.

3. **Maintained Responsiveness**: I've taken care to ensure that the game remains responsive across different devices and screen sizes. The changes made to the "Choose GamePlay Time" section and the overall game interface should adapt well to various screen dimensions.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

I have applied the changes and tested them out in my local machine. I have played the game using different time frames, and it starts with, pauses, ends and plays out in expected manner (the expected time frame and duration). I have also seen to it so that the responsiveness is not compromised.

## Additional notes

The main chnges are the files : main.html, main.css and main.js under assets/ folder and in the README.md file to reflect the new display for the "Choose GamePlay Time Box".

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
GamePlayTime Box Customized

### CODE REVIEW

**Comment by Rakesh9100** [comment]
When we are using the slider for changing the time while choosing, the time change should be visible while sliding the slider @SoumyadevSaha Pls work on it

**Comment by SoumyadevSaha** [comment]
> When we are using the slider for changing the time while choosing, the time change should be visible while sliding the slider @SoumyadevSaha Pls work on it

fixed : the time change is now getting reflected in real time while sliding the slider. Pls check @Rakesh9100

**Comment by Rakesh9100** [comment]
Good Work!! Congrats on getting your quality PR merged to this repo under SLoP 3.0 🥳🎉 @SoumyadevSaha 

`give @SoumyadevSaha 150 points`

**Comment by SoumyadevSaha** [comment]
> Good Work!! Congrats on getting your quality PR merged to this repo under SLoP 3.0 🥳🎉 @SoumyadevSaha
> 
> `give @SoumyadevSaha 150 points`

Thank you so much 😁

**Comment by Rakesh9100** [comment]
give @SoumyadevSaha 150 points

**Pull request merged**
