### PR TITLE
Added interactive mouse pointer

### LINKED ISSUE #166: Enhancing User Experience with Interactive Mouse Pointer
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

The current gaming website utilizes a standard mouse cursor, and I believe we can significantly enhance the user experience by introducing an interactive and themed mouse pointer. An engaging cursor can add an extra layer of immersion and excitement for users navigating the gaming interface.

I would like to work on the same, so please assign it to me.

### Screenshots

This is the pointer I want to incorporate on the landing page. 

[screen-capture (9).webm](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/73214455/a8ae49c2-86fe-4a84-ba8e-2b69ebcdce12)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by ayushichoudhary-19**
# Fixes Issue🛠️
This PR resolved the issue: #166 

Closes #166 

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
[screen-capture (14).webm](https://github.com/Rakesh9100/Click-The-Edible-Game/assets/73214455/6b582586-6d7e-4ae0-8efa-fc1f1f124afd)

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Custom cursor are not visible when instruction box is popped up, play pause box comes up, also when hovered on Time, Score. Fix these pls @ayushichoudhary-19

**Comment by Rakesh9100** [comment]
Custom cursor is not visible when instruction box is popped up, play pause box comes up, also when hovered on Time, Score. Fix these pls @ayushichoudhary-19 
Also cursor is laggy which should be fixed.

**Comment by ayushichoudhary-19** [comment]
@Rakesh9100 Issues are resolved.

**Comment by Rakesh9100** [comment]
Good, Merged!! Congrats on getting your PR merged to this repo under SWOC S4 🎉🎉 @ayushichoudhary-19

**Pull request merged**
