### PR TITLE
#48 issue: Background changed

### LINKED ISSUE #48: Enhance the color
Enhance the background color of just the Landing Page (refer below).

image

### PR DESCRIPTION
**Pull request by AK-shat-JAIN**
# Fixes Issue🛠️

Closes #48 

# Description👨‍💻 

# Type of change📄

- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷
https://user-images.githubusercontent.com/84455686/219884043-7e365908-5aa0-450e-bc89-586ca883fcbb.png
https://user-images.githubusercontent.com/84455686/219884068-64ed2776-e15b-4e6b-90ab-6e3684b673c4.png

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Just edit the file in this PR only and change the border width to 16px @AK-shat-JAIN

**Comment by AK-shat-JAIN** [comment]
@Rakesh9100 Please review I have solved conflicts

**Comment by Rakesh9100** [comment]
Good, I think now you are clear on how to resolve conflicts. 🎉

**Comment by AK-shat-JAIN** [comment]
@Rakesh9100  thanks for merge 
yes this teach me many new things as I am beginning in to open source

**Pull request merged**
