### PR TITLE
Instruction box made responsive

### LINKED ISSUE #210: [Bug] Responsiveness of the instruction box
### Description

The lets get started button is not shown properly and it is not clear from the view of the screen shot.

### Screenshots

Screenshot from 2024-01-15 22-26-50

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by shivam101203**
# Fixes Issue🛠️ #210 

Closes #210

# Description👨‍💻 

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)

# How this has been tested✅

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷
before
Screenshot from 2024-01-17 03-30-43

after
Screenshot from 2024-01-17 03-26-53

### CODE REVIEW

**Comment by shivam101203** [comment]
#210 bug removed sir

**Comment by shivam101203** [comment]
Please review and merge it

**Comment by shivam101203** [comment]
please merge the pr sir

**Comment by Rakesh9100** [comment]
Hey @shivam101203 Don't comment again and again, will check and merge!!

**Comment by shivam101203** [comment]
Okk sir

**Comment by shivam101203** [comment]
I would make it responsive

**Comment by shivam101203** [comment]
So may  I close pull request I have made button looks clearly

**Comment by Rakesh9100** [comment]
No, first show the demo and screenshots here of your changes @shivam101203

**Comment by shivam101203** [comment]
before
old
after
new

**Comment by shivam101203** [comment]
Sir please gave response may I close pull request or else

**Comment by shivam101203** [comment]
@Rakesh9100 please check and explain what should I do further

**Comment by Rakesh9100** [comment]
image
## In website, the button looks like this!

image
## But after your changes, it is looking like this @shivam101203

**Comment by shivam101203** [comment]
Okk sir

**Comment by shivam101203** [comment]
Actually button have same class so that's happened

**Comment by Rakesh9100** [comment]
But this should not happen, you have to work accordingly.

Don't change anything in the files except just adding media queries for small screen sizes @shivam101203

**Comment by shivam101203** [comment]
Sorry for this sir

**Comment by Rakesh9100** [comment]
Are you resolving this @shivam101203

**Comment by shivam101203** [comment]
Yes sir

**Comment by shivam101203** [comment]
Sir I have done #317 please merge that

**Comment by shivam101203** [comment]
Sir please handle this issue to anyone else as I have made it wrong

**Pull request closed without merging**
