### PR TITLE
Redirecting to the Game Screen Fixed

### LINKED ISSUE #239: [Bug] Redirecting to the Game Screen
### Description

When Clicked on any of the Edible we are not able to proceed to play the game. I would like to fix this issue.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by antilneeraj**
# Fixes Issue🛠️

- Closes #239 

# Description👨‍💻 

Fixed the ISSUE - #239 (When Clicked on any of the Edible we are not able to proceed to play the game) Now the Functioning of the website is Normal.

# Type of change📄

- [x] Bug fix (non-breaking change which fixes an issue)

# How this has been tested✅

I have tested it locally using Unit, Alpha & Beta Testing.

# Screenshots/Video 📷

https://github.com/Rakesh9100/Click-The-Edible-Game/assets/98269887/9a3c6f77-38bd-422c-bf06-984cd70248f8

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I am an Open Source Contributor

### CODE REVIEW

**Comment by antilneeraj** [comment]
@Rakesh9100 The PR is ready for review and merge. Kindly review the PR and Give you Feedback.

**Comment by antilneeraj** [comment]
Additionally, I kindly request you to consider adding the `JWOC` and necessary `Difficulty` Label to this PR

**Comment by Rakesh9100** [comment]
Pls attach the demo video or screenshots in the PR description @antilneeraj

**Comment by antilneeraj** [comment]
@Rakesh9100 Done! 👍🏼

**Comment by Rakesh9100** [comment]
Merged 🎉 @antilneeraj

**Pull request merged**
