### PR TITLE
enhanced footer

### LINKED ISSUE #129: Updating Footer
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

The footer style should match the standards of a footer.

### Screenshots

Enhancing Footer under JWOC

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by Viveksati5143**
# Fixes Issue🛠️

Closes #129 @Rakesh9100 

# Description👨‍💻 

Enhanced footer to a better cool look
Open to any better color suggestions✅

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷
image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Change not required @Viveksati5143

**Comment by Viveksati5143** [comment]
> Change not required @Viveksati5143 Try to work on some good issues

@Rakesh9100 assign me issues to work at

**Comment by Rakesh9100** [comment]
Now, JWOC is going to end. So it's difficult to open any new issues. Hope you understand @Viveksati5143

**Comment by Viveksati5143** [comment]
Sure, the only reason I created this small issue @Rakesh9100

**Comment by Rakesh9100** [comment]
But the website footer is already good. There is no mentioned standard to keep footer text in middle. It is justified according to the website design and can be aligned anywhere.

**Comment by Viveksati5143** [comment]
Sure @Rakesh9100 It was my bad decision wasting time on this dumb project.
You definitely can never be a good mentor lmao.

**Comment by Viveksati5143** [comment]
Deleting wont hide the truth lmaoooooo @Rakesh9100

**Pull request closed without merging**
