### PR TITLE
#59 issue resolved : added a function to stop sudden reloading during…

### LINKED ISSUE #59: Prevent Refresh
Add a function that will prevent Refreshing the page when user plays the game or on the playing screen. Both Ctrl+R and F5 should be prevented.

### PR DESCRIPTION
**Pull request by AK-shat-JAIN**
… game running

# Fixes Issue🛠️

Closes #59 

# Description👨‍💻 

 added a function to stop sudden reloading during game running

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)

# How this has been tested✅

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷
image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
You have to make a function script such that when Ctrl+R or F5 is pressed by the user on the gameplay page, then it prevents the page from refreshing @AK-shat-JAIN

**Comment by Rakesh9100** [comment]
You have to make a function script such that when Ctrl+R or F5 is pressed by the user on the gameplay page, then it prevents the page from refreshing @AK-shat-JAIN

**Comment by AK-shat-JAIN** [comment]
sr it's doing the same thing. Taking users's confirmation to refresh but progress is not saved

**Comment by Rakesh9100** [comment]
> sr it's doing the same thing. Taking users's confirmation to refresh but progress is not saved

No, it's not. I have tried the preview in chrome and when Ctrl+R or F5 is pressed it takes to the home page directly. It should give the warning.

**Comment by Rakesh9100** [comment]
Have you checked for both combinations, Ctrl+R and F5 ?

**Comment by AK-shat-JAIN** [comment]
Yes sr its worked for both

**Comment by Rakesh9100** [comment]
I checked your code, so try to use keydown event in the window object and set key code of F5 and Ctrl so, when anyone triggers the key it brings up the warning. When refresh will be confirmed as true, the window will reload.
This is the best method to prevent refreshing and will work everywhere. @AK-shat-JAIN

**Comment by AK-shat-JAIN** [comment]
Ok @Rakesh9100 
Please give me some time first to learn about it then I will make proper changes

**Comment by Rakesh9100** [comment]
Okay, since this is an easy task but still extension is given to you. Don't worry. Learn and implement @AK-shat-JAIN

**Comment by AK-shat-JAIN** [comment]
Thanks @Rakesh9100 for understanding my concern

**Pull request closed without merging**
