### PR TITLE
[Feature] Added Functionality to Display Scores in Descending order

### LINKED ISSUE #123: [Feature] Displaying All the Scores in Descending Order
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Workflow : 
- [x] Create an `Scores` Element in the DOM
- [x] Initialize an `Scores Array` that will keep storing the Player's Scores
- [x] Sort the `Scores Array` in reverse order to make sure it's descending order.
- [x] Serve the updated Element back to the DOM.

### Screenshots

_No response_

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by pooranjoyb**
# Fixes Issue🛠️

Added functionality to display all scores in descending order.

Closes #123 

# Description👨‍💻 

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

scores

### Would be glad if you'd merge this PR @Rakesh9100 😄

### CODE REVIEW

**Comment by Rakesh9100** [comment]
It will be good if you display all the scores with its playtime similar to this format: @pooranjoyb 

| Your Scores | PlayTime |
|:-----:|:-----:|
| 55 | 1:00 min |
| 25 | 30sec |
| 10 | 2:00 min |

**Comment by pooranjoyb** [comment]
okay, I'm onto it.

**Comment by Rakesh9100** [comment]
Status @pooranjoyb

**Comment by pooranjoyb** [comment]
Really Sorry to say, but its turning onto the same thing as on the previous issue. Like when I'm trying to access the state of button inside the `chooseGameplayTime()` function, the variable is not getting updated and i really don't know the reason why. I have been trying to fix this but all in vain. I am sorry. @Rakesh9100 
Possibly won't be able to fix that. 😓

**Comment by Rakesh9100** [comment]
Okay, no issues. So, closing the PR @pooranjoyb

**Comment by Rakesh9100** [comment]
Okay, no issues. @pooranjoyb

**Comment by pooranjoyb** [comment]
Could be great if you merge this PR @Rakesh9100

**Comment by Rakesh9100** [comment]
Merged 🎉 @pooranjoyb

**Pull request merged**
