### PR TITLE
#34 issue solved : Added Landing page with Animation

### LINKED ISSUE #34: Adding animation to Landing Page
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Landing page looks very normalistic
Want to add animation effect in it such that the text "Play with your Favorite Edible🎮" will animate and come like in this website 
https://ak-shat-jain.github.io/FoodGenix/
that's also created by me

JWOC mentee

### Screenshots

_No response_

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by AK-shat-JAIN**
# Fixes Issue🛠️

Closes #34 

# Description👨‍💻 

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

created svg paths and animate them

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷
image

### CODE REVIEW

**Comment by AK-shat-JAIN** [comment]
Sr @Rakesh9100 is there anything I have to add more on it?

**Comment by Rakesh9100** [comment]
Pls mention the issue number closed in the description after Closes # @AK-shat-JAIN

**Comment by Rakesh9100** [comment]
Nice!! 🎉

**Comment by AK-shat-JAIN** [comment]
Thanks !!🤩

**Pull request merged**
