### PR TITLE
Feature Enhancement: Adding bombs and lives to the game

### LINKED ISSUE #134: Enhancement: Add explosive bombs along with edibles in the game
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Feature Enhancement @ SloP 3.0
I've made an enhancement to the "Click The Edible Game" by introducing bombs and lifelines to the game. Currently, the game is about clicking as many edibles as possible within a set time frame. This enhancement adds a new challenge to the game.

### Proposed Changes
- [x] Introduce bombs as a part of the game.
- [x] Limit the number of active bombs on the screen at any given time (MAX_number of bombs).
- [x] When a user clicks an edible, there's a 50% chance a new bomb appears, provided the number of active bombs is below the maximum limit.
- [x] Bombs have a limited lifespan, and if they are not clicked within a certain time, they disappear.
- [x] Set a rule that if a user clicks on 3 bombs, the game is over, regardless of the remaining time on the timer.
- [x] Implement UI elements to display the number of lives left.
- [x] Integrate new sound and animation on bomb explosion. 

### Motivation
This change adds an exciting twist to the game by introducing the risk of bombs. Players need to balance clicking edibles for points and avoiding bombs to stay in the game. It adds an element of strategy and challenges players to manage their moves effectively.

### Additional Notes
Please review this enhancement request, and if it aligns with the project's goals and standards, I'd be happy to create a pull request to implement these changes. Your feedback and guidance are highly appreciated.

### Screen Shot 1
issue2_1

### Screen Shot 2
issue2_2

### Screen Shot 3
issue2_3

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by SoumyadevSaha**
# Fixes Issue🛠️

Closes #134 

# Description👨‍💻 

## Aplied Changes

1. **Introduction of Bombs**: I have included bombs in the game, i.e, while the edibles appear, some bombs might also appear with a 50% probability. The maximum number of bombs that can be on the screen is limited to 5, to avoid crowding. Also, the lifespan of each bomb ranges between 1 to 6 seconds.

2. **Updated Game Logic**: To accommodate the Introductions of bombs and the lives of the player, to allow gameover condition on all the lives getting wasted, has all been implemented.

3. **Addition of lives**: The player will have a max of 3 lives when playing, on clicking a bomb one live is lost. When all 3 lives are lost, it is game over.

4. **Inclusion of assets**: Some assets, mainly, the image of the bomb, the image when a bomb explodes, and the sound played when the bomb explodes has been included.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

I have applied the changes and tested them out in my local machine. I have played the game muliple times to ascertain the randomness of the appearance of the bombs, and also seen to the fact that on clicking 3 bombs the game gets over properly and without bugs.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

## Screen-shot 1
issue2_pr1

## Screen-shot 2
issue2_pr2

## Screen-shot 3
issue3_pr3

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Nice work!! Merged 🎉🥳 @SoumyadevSaha

**Comment by Rakesh9100** [comment]
Nice work!! Merged 🎉🥳 @SoumyadevSaha 

give @SoumyadevSaha 150 points

**Comment by SoumyadevSaha** [comment]
> Nice work!! Merged 🎉🥳 @SoumyadevSaha
> 
> give @SoumyadevSaha 150 points

Thankyou @Rakesh9100 😊

**Comment by Rakesh9100** [comment]
give @SoumyadevSaha 150 points

**Pull request merged**
