### PR TITLE
108 highscore

### LINKED ISSUE #108: [Feature] Adding High Score on Game Over
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

## Outcome
- This will increase overall quality of the game and give it a professional outlook.
- Player will try to beat his own Highscore, resulting a player to spend more time in the Game.

## Workflow : 
**It will take some time to complete this task**. 
It's quite difficult to execute as 
- we have to store the Highscore and update it each time with the new score
- comparing with previous scores
- Also make sure that scores will be invalid for other timers and is valid for one particular gameplay time.
- We will have to reset the Highscore if player chooses a separate time of gameplay. 

### Screenshots

_No response_

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by pooranjoyb**
# Fixes Issue🛠️

### Closes #108 

# Description👨‍💻 

## Workflow : 

- [x] Stored the Highscore in an array called `scoresArray` and updated it each time with the New Score
- [x] Created a prototype method `max()` that finds the maximum element in an array.
- [x] Rendered the returned value from the method `max()` to the client.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Demonstrating Video : 
[demo46.webm](https://user-images.githubusercontent.com/90945182/224564624-076aadd4-5a57-4288-8ae9-27c0bfe5ff2d.webm)

### Would be glad if you could merge this PR @Rakesh9100  😄 👍

### CODE REVIEW

**Comment by Rakesh9100** [comment]
If the player choses other gameplay time on restarting, will high score reset or not ? @pooranjoyb I suppose every gameplay time will be considered and compared which should not

**Comment by pooranjoyb** [comment]
Ya I've tried that part but was facing some issues as it was leading to a race condition leading to breaking of the function. But I am still researching to fix that part. If you want, you can merge this PR & I would raise another issue to fix it. I am onto it. Give me a day I will surely be available with the fix. @Rakesh9100 😃

**Comment by Rakesh9100** [comment]
Okay, try it out.
One more thing that you should save the scores and display all the scores in the descending order being high score on the top or implement a feature My Scores where user can see his/her every scores until he/she remains on the game @pooranjoyb

**Comment by pooranjoyb** [comment]
Ok, thanks for the advice. Will be pushing commits in this branch then and will let you know the updates in discord tomorrow. @Rakesh9100

**Comment by Rakesh9100** [comment]
If you thought of to work on these by creating new issues, then I will merge so, specify in case any issue you face and assistance you need @pooranjoyb

**Comment by pooranjoyb** [comment]
#### I am planning to fix the resetting of `High scores` on different gameplay time in this `PR itself` but as you said you would like to see some more enhancements like 
- Displaying all the scores in the descending order and
- A feature of my Scores where user can see his/her every scores until he/she remains in the game

### I would wish to open more issues to apply those enhancements. Will that be good bhaiyaa? @Rakesh9100

**Comment by Rakesh9100** [comment]
Yes, you can fix resetting of high scores in this PR and next enhancements in new issue and PR @pooranjoyb

**Comment by pooranjoyb** [comment]
Thank you bhaiyaa 😄 ❤️ @Rakesh9100

**Comment by Rakesh9100** [comment]
What's the issue being faced ?

**Comment by pooranjoyb** [comment]
> What's the issue being faced ?

When I create a global `var` and try to update inside a function, I don't know but it is not getting updated.

**Comment by Rakesh9100** [comment]
I think this update inside function will tend to break it. Okay, will see it myself. Will merge this PR.
Will you continue to work for the all scores and descending order enhancement ? @pooranjoyb

**Comment by pooranjoyb** [comment]
Yes I will create another issues to add other Enhancements. THANK YOU. @Rakesh9100 :heart:

**Comment by Rakesh9100** [comment]
Good work!! @pooranjoyb

**Pull request merged**
