### PR TITLE
Updated the Instructions box text and Readme.md screenshot

### LINKED ISSUE #139: Update: Instruction box in the game
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

## Updating the instruction box in the game @SloP 3.0
Update the Instruction box content in the game to let players know about introduction of the new feature (the bombs) and that in case they click on a bomb, it is not an immediate game over, but they still will have 2 lives remaining.

## New instruction might look something like:

Screenshot 2023-10-27 at 8 55 52 PM

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by SoumyadevSaha**
# Fixes Issue🛠️

Closes #139 

# Description👨‍💻 

## Applied changes:
1. **Updated the instrusctions box**: Notified the players about the new feature; the bombs and lives in the game.
2. **Updated the instruction box screen-shot in readme.md**: The new updated instruction box's screenshot has been pasted in the readme.md

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Tested in the local machine, the changes are being reflected and displayed successfully.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
Screenshot 2023-10-29 at 5 57 35 PM

### CODE REVIEW

**Comment by Rakesh9100** [comment]
What is the update in the main.js file? @SoumyadevSaha

**Comment by SoumyadevSaha** [comment]
> What is the update in the main.js file? @SoumyadevSaha

There, in the closeInstruction() function, I saw that in all cases, the isRunning variable was made to be 1. but that shouldn't be the case, otherwise, it will interfare with the bgm playing.

**Comment by Rakesh9100** [comment]
Okay, Merged!! 🥳 @SoumyadevSaha

**Comment by Rakesh9100** [comment]
give @SoumyadevSaha 25 points

**Pull request merged**
