### PR TITLE
Fixed the overlapping of footer with edible components

### LINKED ISSUE #180: [Bug] Footer is overlapping with edible section components
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Destination:
1) Click "play the game:

Bug: The components of edible vegetable are overlapping with footer. If you scroll down, the problem persists with other components also.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by KhushiRawat29**
# Fixes Issue🛠️

Closes #180

# Description👨‍💻 

No extra dependencies are required. The footer is no longer overlapping with the edible section components. Changes were made in main.html

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)

# How this has been tested✅

1) Open the the repository on your text editor (for eg, VS code)
2) Click on Live Server
3) Navigate to Local host .
4) Click on "Play game"
5) Now the scroll the webpage, you will notice that there is no overlapping between footer and edible icons.

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I am an Open Source Contributor

# Screenshots/GIF📷

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls delete the package-lock.json file and also why there are changes in `index.html` file @KhushiRawat29

**Comment by KhushiRawat29** [comment]
I didn't make any changes in index.html. May be I have added space somewhere.

**Comment by KhushiRawat29** [comment]
I've deleted package.json. Shall I push the changes again.

**Comment by Rakesh9100** [comment]
> I didn't make any changes in index.html. May be I have added space somewhere.

I mean to say `main.html` file @KhushiRawat29

**Comment by KhushiRawat29** [comment]
Actually this is my first open source contribution. I am a little confused. The code that was to changed lies in main.html, so I made changes into that file and then committed it. Can you please explain the issue with the changes?

**Comment by Rakesh9100** [comment]
Okay no worries. Just delete that package file and push and make the commit @KhushiRawat29

**Comment by KhushiRawat29** [comment]
okay

**Comment by KhushiRawat29** [comment]
Its done

**Comment by Rakesh9100** [comment]
Good, Merged!! Congrats on getting your PR merged to this repo under SWOC S4 🎉🎉 @KhushiRawat29

**Comment by KhushiRawat29** [comment]
Thanks for your cooperation.

**Pull request merged**
