### PR TITLE
Styling enhanced

### PR DESCRIPTION
**Pull request by YashBawa**
#1 🛠️ 

- [] New feature (styling has been updated,hover effect color, text and heading colors added )

# Checklist✅ 

- [Yes] My code follows the style guidelines of this project
- [Yes] I have performed a self-review of my own code
- [yes] I have added demonstration in the form of GIF/video file
- [yes] I am an Open Source Contributor

# Screenshots/GIF📷
Hover color updated
image
Basic coloring updated:-
image

### CODE REVIEW

**Comment by YashBawa** [comment]
Please review and verify the above PR. Thank you

**Comment by Rakesh9100** [comment]
Update the issue number you have worked by adding #issuenumber. @YashBawa

**Comment by YashBawa** [comment]
@Rakesh9100 added the issue number.

**Comment by Rakesh9100** [comment]
Nice 👍, Merged !! @YashBawa

**Pull request merged**
