### PR TITLE
Added Drag & Drop Feature and Redesigned the Upload Section

### LINKED ISSUE #219: [Feature] Add a Drag & Drop Feature and Redesign of the Upload Section
### Description

- I'll redesign the Image upload Area to look more modern. 
- Add a handy drag-and-drop feature for a smoother experience.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by antilneeraj**
# Description👨‍💻 

This pull request addresses issue #219 by introducing a Drag & Drop feature, providing users with a seamless and interactive way to upload content. Additionally, the Upload Section has undergone a redesign to improve its visual appeal and usability.

# Fixes Issue🛠️

Closes #219 

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# Changes 

- Added a Drag & Drop feature to enhance user experience.
- Implemented a redesign of the Upload Section for a more intuitive and modern look.

# How this has been tested✅

I have done Alpha, Beta & Unit Testing

# Screenshots/GIF📷

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I am an Open Source Contributor

### CODE REVIEW

**Comment by antilneeraj** [comment]
@Rakesh9100 This pull request is ready for review and merge. Additionally, I kindly request you to consider adding the "JWOC" and "Difficulty" labels to this pull request.

Thank you for the opportunity to contribute to the project!

**Comment by Rakesh9100** [comment]
Pls make it responsive for smaller screens @antilneeraj

**Comment by Rakesh9100** [comment]
Good, Merged!! Congrats on getting your PR merged to this repo under JWOC 🎉🎉 @antilneeraj

**Comment by antilneeraj** [comment]
Thankyou 🙂 @Rakesh9100

**Comment by Rakesh9100** [comment]
Hey @antilneeraj After your changes, we are unable to select any edible and move forward to the playing screen, fix it ASAP!!

**Pull request merged**
