### PR TITLE
Add Event Listener And Music Toggle Icon

### PR DESCRIPTION
**Pull request by Kapileswar-Moharana**
Issue Title: Adjust The No Of Bomb With Icon
Issue no: #169

Close: #169     

## Checklist:
- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy-to-understand README.md
- [x] Add an event listener to the window to handle autoplay restrictions
- [x] Add A Toggle Volume Button For Music On Off

## Pull Request Description:

I Have Added a Music Toggle Button and updated the JavaScript Code To Control The Autoplay Restrictions. The WebSite According To The Project And Test It For Different Devices As It Works Well.

## Changes Made:

- Provided explanations for each section.
- Detailed Description:
- Added Music Toggle  Button
- Update The JavaScript Code To Control The Autoplay Restrictions

## Screenshots

Screenshot 2024-01-07 024519
Screenshot 2024-01-07 024500
Screenshot 2024-01-07 024540

### CODE REVIEW

**Comment by Kapileswar-Moharana** [comment]
@Rakesh9100 Check Now Is It Will Be Okay...?
Screenshot 2024-01-07 033526

**Comment by Rakesh9100** [comment]
I can see Sound is not on automatically when page is open which this issue was opened for @Kapileswar-Moharana

**Comment by Kapileswar-Moharana** [comment]
> I can see Sound is not on automatically when page is open which this issue was opened for @Kapileswar-Moharana

@Rakesh9100 i have Checked It And Got To Know That Due To Autoplay Restrictions, This DisFunction Happens In some of The Devices That's Why You Can See That I have Added an " event listener to the window to handle autoplay restrictions".

**Comment by Kapileswar-Moharana** [comment]
> > I can see Sound is not on automatically when page is open which this issue was opened for @Kapileswar-Moharana
> 
> @Rakesh9100 i have Checked It And Got To Know That Due To Autoplay Restrictions, This DisFunction Happens In some of The Devices That's Why You Can See That I have Added an " event listener to the window to handle autoplay restrictions".



> I can see Sound is not on automatically when page is open which this issue was opened for @Kapileswar-Moharana

And This Autoplay Restriction You Can Toggle To Make This Happen...In Some Devices Its already Been Off...

**Comment by Kapileswar-Moharana** [comment]
> > I can see Sound is not on automatically when page is open which this issue was opened for @Kapileswar-Moharana
> 
> @Rakesh9100 i have Checked It And Got To Know That Due To Autoplay Restrictions, This DisFunction Happens In some of The Devices That's Why You Can See That I have Added an " event listener to the window to handle autoplay restrictions".

 If you have autoplay restrictions on your browser, this approach might not work, and you would need to handle user interaction (like a button click) to start the audio.

**Comment by Kapileswar-Moharana** [comment]
@Rakesh9100 One More Thing I Have Already updated the JavaScript Code As Soon As The Page Loads Then The BGM Will Start Playing...

**Comment by Rakesh9100** [comment]
Yes, you are right about this autoplay restrictions present in some browsers or devices. This can be fixed by user using the website itself.

Okay, Merged!! 🎉 @Kapileswar-Moharana

**Comment by Kapileswar-Moharana** [comment]
> Yes, you are right about this autoplay restrictions present in some browsers or devices. This can be fixed by user using the website itself.
> 
> Okay, Merged!! 🎉 @Kapileswar-Moharana

Thanks

**Comment by Rakesh9100** [comment]
Ohkk, I didn't notice that the code has been copied from this PR. Pls open up new issues if you want to and I will assign you. This will be taken utmost care from next time that codes don't get copied.

And about closing your PR as I told issue was not assigned to you, so it was closed @cryptocat8

**Comment by Rakesh9100** [comment]
Ohkk, I didn't notice that the code has been copied from this PR. Pls open up new issues if you want to and I will assign you. This will be taken utmost care from next time that codes don't get copied.

You are warned to not copy the codes and not to work on someone else issue unless you are assigned to @Kapileswar-Moharana 

And about closing your PR as I told issue was not assigned to you, so it was closed @cryptocat8

**Comment by Rakesh9100** [comment]
Ohkk, I didn't notice that the code has been copied from this PR. Pls open up new issues if you want to and I will assign you. This will be taken utmost care from next time that codes don't get copied.

And about closing your PR as I told issue was not assigned to you, so it was closed @cryptocat8 

You are warned to not copy the codes and not to work on someone else issue unless you are assigned to @Kapileswar-Moharana

**Comment by Kapileswar-Moharana** [comment]
> @Rakesh9100 this is wrong, this guy just copied my codes and pushed it. My pull request was closed and not merged and his is merged. I did that code because ut was active for so long and i thought it was not being completed.

@cryptocat8 DaDa There Is Many More Point
- First Of All You Should Have To Ask For The Assign Issue...
- You Can Not Directly Raise A PR To Any Of The Repo...There Are some rules And regulations...
- 3rd Your Raised PR Which Was No Linked To The Issue Was Created
- You Created A Toggle Bottom The Issue Was About To Immediate Start Of Music... First Try To Understand The Issue Before Raising PR
- And About Me, I Already Solved My Issue And Then I Just Made An Enhancement Yes That's True I Saw your code But Not Copied It modified It To some How
- Saw Your Designing Code And Mine Before Yelling To Some One
- First Come With All Rules And Regulation Ask For Issues Then You Are In Full Rights To Raise PR
- Still, You Are In The Wrong Mindset That The Project Admin Closed Your PR Because You Are Not Assigned And The PR Is Not About Toggle Button If You Are Still yelling At Me That I copied, No Worries I am Not Like You That I know This Only Way I can Modify It By My OWN, 
- If Still, You Have Issues Then I will Reset These Issues By Solving Only Assigned Issue...
- Any Queries... Sir, Please Follow The rules...

**Comment by Rakesh9100** [comment]
Please maintain the decorum of open source and github @Kapileswar-Moharana 

And yes, its true that code is not copied as I just checked and compared his PR and your PR code @cryptocat8 which are totally different. You can just say that idea is copied.

No need to reset issue/PR @Kapileswar-Moharana

**Comment by Rakesh9100** [comment]
No further discussions as I already mentioned that this would be taken care at prior basis from the next time. Do create your own new issues if you want to contribute and I will assign you if its valid @cryptocat8

**Comment by Kapileswar-Moharana** [comment]
> Ohkk, I didn't notice that the code has been copied from this PR. Pls open up new issues if you want to and I will assign you. This will be taken utmost care from next time that codes don't get copied.
> 
> And about closing your PR as I told issue was not assigned to you, so it was closed @cryptocat8
> 
> You are warned to not copy the codes and not to work on someone else issue unless you are assigned to @Kapileswar-Moharana


> Please maintain the decorum of open source and github @Kapileswar-Moharana
> 
> And yes, its true that code is not copied as I just checked and compared his PR and your PR code @cryptocat8 which are totally different. You can just say that idea is copied.
> 
> No need to reset issue/PR @Kapileswar-Moharana

@Rakesh9100 Yes Sir I Think You Closed That PR Yet He Is Not Create Issue Regarding It so I Improve it to...Toggle Buttton... 
- But I also Think About The Same To create Issue But app Bole Ki First Solved All Assign Issues and That's Why I didid Not Create Besides All ... i Should Have To Ask For It...

**Pull request merged**
