### PR TITLE
Add Footer

### LINKED ISSUE #66: Add Footer
Add a responsive footer to the website and make sure it should not affect any page screen or gameplay.

### PR DESCRIPTION
**Pull request by Hritik1503**
# Fixes Issue🛠️

Closes #66 

Closes #

# Description👨‍💻 

I will add footer in the website of click the edible game under jwoc.

# Type of change📄

Added footer

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Design it. Don't make it this much simple. It's neither visible nor looking good.

**Comment by Hritik1503** [comment]
Please tell me what type of design black and white

**Comment by Hritik1503** [comment]
I will change according to your request please check and tell me if any
changes required

**Comment by Rakesh9100** [comment]
It's just a footer. You can search any 2-3 good projects on google and see how they have designed a footer.

**Comment by Hritik1503** [comment]
Check this is good or not

**Comment by Rakesh9100** [comment]
Yes fine, do check in the dark them too and change color if needed. And make sure it is responsive.

**Comment by Hritik1503** [comment]
Yes I will check in dark and then send you screenshot

**Comment by Hritik1503** [comment]
I will solve this issue under jwoc

**Pull request merged**
