### PR TITLE
updated readme file with content, hyperlinks and updated screenshots.

### PR DESCRIPTION
**Pull request by Code1705**
with content, updated screenshots and hyperlinks.

# Fixes Issue🛠️

Closes #

# Description👨‍💻 

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷

### CODE REVIEW

**Comment by Code1705** [comment]
could you please merge my PR I have commited the changes?

**Comment by Rakesh9100** [comment]
Attach the changes Screenshot and mention the issue closed by this PR.

**Comment by Rakesh9100** [comment]
You can't push to the main branch of anybody's repository directly. You have to create your own new branch and then push the changes to it. Go through [this link](https://github.com/Rakesh9100/Click-The-Edible-Game#getting-started) properly. @kushaljgec2025

**Comment by Rakesh9100** [comment]
You can't push to the main branch of anybody's repository directly. You have to create your own new branch and then push the changes to it. Go through [this link](https://github.com/Rakesh9100/Click-The-Edible-Game#getting-started) properly. @Code1705

**Pull request closed without merging**
