### PR TITLE
Added Progress Indicator With Back-Top Button

### PR DESCRIPTION
**Pull request by Kapileswar-Moharana**
Issue Title: Add Back To Top Button
Issue no: #171 

Close: #171 

## Checklist:
- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy-to-understand README.md
- [x] The Favicon Section works well on different devices.

## Changes Made:

- Added meta information to improve SEO and rendering compatibility.
- Organized the HTML code for better readability.
- Provided explanations for each section.
- Detailed Description:
- Added Media Queries
- Added Favicon
- Added Back To Top Button

## Screenshots

image

### CODE REVIEW

**Comment by Kapileswar-Moharana** [comment]
@Rakesh9100 Check It Is It Okay Now

**Comment by Rakesh9100** [comment]
Yes it is okay but I want you to add the loader around the arrow as done in `Beautiify` Project @Kapileswar-Moharana

**Comment by Kapileswar-Moharana** [comment]
> Yes it is okay but I want you to add the loader around the arrow as done in `Beautiify` Project @Kapileswar-Moharana

Let me Check....Sir

**Comment by Kapileswar-Moharana** [comment]
> Yes it is okay but I want you to add the loader around the arrow as done in `Beautiify` Project @Kapileswar-Moharana

@Rakesh9100 Can You Give Me A Screenshot ... Of That Diid Not Get You... Abhi Banaa Detaa Hun Kyaa Chtee Ho... Bass Thodaa Jaldii Boliye...

**Comment by Rakesh9100** [comment]
Check the scroll to top button of this project website [Beautiify](https://beautiify.netlify.app) and work accordingly @Kapileswar-Moharana

**Comment by Kapileswar-Moharana** [comment]
> Check the scroll to top button of this project website [Beautiify](https://beautiify.netlify.app) and work accordingly @Kapileswar-Moharana

@Rakesh9100 Ohh That One's Called The "Progress Indicator " I Think... Yes, I will Do...

**Comment by Kapileswar-Moharana** [comment]
> > Check the scroll to top button of this project website [Beautiify](https://beautiify.netlify.app) and work accordingly @Kapileswar-Moharana
> 
> @Rakesh9100 Ohh That One's Called The "Progress Indicator " I Think... Yes, I will Do...

@Rakesh9100 Hey's been Approximately 3:00 I have to do Some Other Work Too... So Give Some Time To Do This Enahancemnet around Tomorrow Evening... I will Do This...

**Comment by Rakesh9100** [comment]
Okay, take your time @Kapileswar-Moharana

**Comment by Rakesh9100** [comment]
Any update @Kapileswar-Moharana

**Comment by Kapileswar-Moharana** [comment]
> Any update @Kapileswar-Moharana
@Rakesh9100 Yes Sir Doing This Stuff...

**Comment by Rakesh9100** [comment]
Status @Kapileswar-Moharana 

Resolve the conflicts as well.

**Comment by Kapileswar-Moharana** [comment]
> Status @Kapileswar-Moharana
> 
> Resolve the conflicts as well.
Wil Open PR By Today...will solve the conflict as well don't worry...m Now working on another issue of yours after completing that one I will come to this...

**Comment by Kapileswar-Moharana** [comment]
@Rakesh9100 Check It 
Screenshot 2024-01-08 210847

**Comment by Rakesh9100** [comment]
Change the color of progress indicator to blue in light theme @Kapileswar-Moharana

**Comment by Kapileswar-Moharana** [comment]
> Change the color of progress indicator to blue in light theme @Kapileswar-Moharana 
@Rakesh9100 i Though Pink Will Suits More... Wait m Changing

**Comment by Rakesh9100** [comment]
But it is not visible properly, put blue or some color which is visibled properly in the light theme @Kapileswar-Moharana

**Comment by Rakesh9100** [comment]
image

Back to Top button should not come when we are in the gaming screen, it should only be there on selection of edible screen @Kapileswar-Moharana

**Comment by Rakesh9100** [comment]
Open source is for learning and contributing only. So don't worry if you won't be able to fix that. I will merge and open up a new issue for that @Kapileswar-Moharana

**Comment by Kapileswar-Moharana** [comment]
@Rakesh9100 Wait sir let me try this one first itni asanisee give up nhi krtaa hun sirr try to krnee dijiyee iff not thenn I I'll say ... Just give me 2-3 hr.. will fix this...if not thenn you can...

**Comment by Kapileswar-Moharana** [comment]
@Rakesh9100 Sir
- Did Fix The Color
- Merged The Back-To-Top Button With Progress Bar
- Make Responsive For All Devices
- Merged Because Of In Case Of Responsive Its Get Separated That's Why I merged The Both Code...
- Still That Bug Is There That Progress Bar Still There After Moving Another Page But On Clicking It... Its Get Disappear ... I Am Looking For It To Solve ...
- But For Now, Merged These Code...To The Main And I will Or You Just Create One issue Regarding Fixing This ... I also Working On It... To Solve... If Someone Fix This... It is Okay... Otherwise... I will Do It...

**Comment by Kapileswar-Moharana** [comment]
@Rakesh9100 Sorry By Mistakly My Friend's Github Id Was Coauthored there Actually we both doing our College Project And Pushing it to Github From night Time Its Id was there And I Did Not Notice Is There Any Issue...

**Comment by Rakesh9100** [comment]
Fine, no issues if coauthored.

Merged!! 🎉 @Kapileswar-Moharana

**Pull request merged**
