### PR TITLE
changed watermelon image

### LINKED ISSUE #79: Watermelon image dimensions resize
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Image of watermelon looking to be stretched out 
Rewrite its height and width parameter to make it ok

### Screenshots

_No response_

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by AK-shat-JAIN**
# Fixes Issue🛠️

Closes #79 

# Description👨‍💻 

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)

# How this has been tested✅

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷
image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
I suppose the file size is 450kb+? If yes, then compress and keep file less than 50 Kb @AK-shat-JAIN

**Comment by AK-shat-JAIN** [comment]
Ohh Ok sr

**Comment by AK-shat-JAIN** [comment]
Done sr @Rakesh9100

**Comment by Rakesh9100** [comment]
Good!!

**Comment by AK-shat-JAIN** [comment]
Thanks Sr

**Pull request merged**
