### PR TITLE
Pause button animation and light icon hover effect

### PR DESCRIPTION
**Pull request by sagarbee**
#160 Feature Enhancement

# Description👨‍💻 

Include Pause button animation and light icon hover effect + css

# Type of change📄

- pause button animation
- light icon hover effect and color

https://github.com/Rakesh9100/Click-The-Edible-Game/assets/65588552/1a20cd43-5bd2-4629-a1fb-25e3c4f4ff52

https://github.com/Rakesh9100/Click-The-Edible-Game/assets/65588552/a1f9115b-c4f4-4d1b-b75f-99e66169a1ea

### CODE REVIEW

**Comment by Rakesh9100** [comment]
When we are clicking on the sun icon to navigate to light theme, the hover effect and the icon both becomes white and icon is invisible @sagarbee Pls fix this

**Comment by sagarbee** [comment]
Thanks for pointing that out, @Rakesh9100 ! I'll be addressing this issue and submitting a new pull request shortly. Your patience is appreciated, and feel free to let me know if there's anything specific you'd like to see in the fix. 👍

**Comment by Rakesh9100** [comment]
Don't submit a new pull request. Make the new changes and commit in this PR only @sagarbee

**Comment by sagarbee** [comment]
Made some new changes and commit in this PR.

https://github.com/Rakesh9100/Click-The-Edible-Game/assets/65588552/401bf881-e2c6-4080-97b8-143aa6d4658b

**Comment by Rakesh9100** [comment]
Good, Congrats on getting your PR merged to this repo uner SWOC S4 @sagarbee

**Comment by Rakesh9100** [comment]
Good, Congrats on getting your PR merged to this repo uner SWOC S4 🎉 @sagarbee

**Pull request merged**
