### PR TITLE
added some edible items

### PR DESCRIPTION
**Pull request by Daffodilgithub**
# Fixes Issue🛠️ #14 

# Description👨‍💻 

# Type of change
add contents

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I am an Open Source Contributor

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Put the changes screenshot or video @Daffodilgithub

**Comment by Daffodilgithub** [comment]
Screenshot (70)
Screenshot (74)
Screenshot (73)

**Comment by Rakesh9100** [comment]
Everything is going out of the page, pls check again @Daffodilgithub

**Comment by Daffodilgithub** [comment]
Please check it

**Comment by Rakesh9100** [comment]
No, the same issue is there that all the boxes are coming in the next and previous pages and also all the boxes are not working when selecting to play @Daffodilgithub

**Comment by Daffodilgithub** [comment]
I tried but couldn't fix it.  I think a new issue can be opened or please assign it to other mentees.

**Comment by Rakesh9100** [comment]
No problem, you can take up or create a new issue anytime.

**Pull request closed without merging**
