### PR TITLE
#33 issue solved : Added Back icon and Removed Home icon

### PR DESCRIPTION
**Pull request by AK-shat-JAIN**
# Fixes Issue🛠️

Closes #

# Description👨‍💻 

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls attach the SS reference and mention the issue number this PR closes @AK-shat-JAIN

**Comment by AK-shat-JAIN** [comment]
#33 Issue solve 
image
image
image
image

**Comment by Rakesh9100** [comment]
Pls check your code once, because after your update, the restart button is not working.

**Comment by AK-shat-JAIN** [comment]
Sorry Sr and Thanks to figure out this mistake

**Comment by Rakesh9100** [comment]
Good Work!! Congrats on getting your PR merged to this repo 🎉 @AK-shat-JAIN

**Comment by AK-shat-JAIN** [comment]
Thank you 😁🤩

**Pull request merged**
