### PR TITLE
Added transition for the instruction box

### LINKED ISSUE #200: [Style] Add transition for the instruction box
### What's the style idea?

We need to improve the style/animation on the instruction box to make the UI good. Use transition for it.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by antilneeraj**
# Fixes Issue🛠️

- Closes #200 

# Description👨‍💻 

Added Transition to the instruction box when clicked on the instruction button and also added a cross button to close the modal.

# Type of change📄

- [x] Bug fix (non-breaking change which fixes an issue)

# How this has been tested✅

I have tested the changes Locally using alpha, beta & unit testing.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

image
image

### CODE REVIEW

**Comment by antilneeraj** [comment]
@Rakesh9100 The PR is ready for a review and merge. Kindly review it and provide your feedback

**Comment by antilneeraj** [comment]
Hey @Rakesh9100 I have applied the animation to the modal without changing any UI Component. Please Review the PR and share your feedback

**Comment by Rakesh9100** [comment]
The 2nd and 3rd screens instruction box is not appearing on clicking the Instruction button, pls fix  @antilneeraj

**Comment by antilneeraj** [comment]
Hey @Rakesh9100, Please review the PR as i have fixed the modal issue and provide your feedback.

**Comment by Rakesh9100** [comment]
Good, Merged 🎉 @antilneeraj

**Pull request merged**
