### PR TITLE
Feature : Instructions box beautified

### LINKED ISSUE #190: Adjust Styling for "Let's Get Started" Button in Instructions
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

The "Let's get started!!" text in the instruction button is not fitting properly within the button, leading to a layout issue.

### Screenshots
Screenshot from 2024-01-11 01-32-55

Assign this issue under SWoC

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by praptisharma28**
Closes #190

Improved the UI for the instruction page , added animations, gradient, colors, styling padding etc. 
Please add the difficulty level @Rakesh9100 , and iwoc24 tag. I would really appreicate a medium tag i you likeit. Thankyou.

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Hey @praptisharma28 

Why instruction box is changed for only one screen and not for next two screens. Pls do the changes accordingly!!

**Comment by praptisharma28** [comment]
oh ok doing it @Rakesh9100

**Comment by praptisharma28** [comment]
Done @Rakesh9100 . Thankyou for pointing out. :)

**Comment by Rakesh9100** [comment]
image
### Box is colliding with footer on this screen. Do fix.
<br><br>
image
Box is different for this screen and also too down. Keep the instruction box design same for all the screens @praptisharma28

**Comment by Rakesh9100** [comment]
image
### Box is colliding with footer on this screen. Do fix.
<br><br>
image
### Box is different for this screen and also too down. Keep the instruction box design same for all the screens @praptisharma28

**Comment by praptisharma28** [comment]
Done @Rakesh9100

**Comment by Rakesh9100** [comment]
Are you working on the suggested changes @praptisharma28

**Comment by praptisharma28** [comment]
Yes @Rakesh9100 , wait for sometime. I am working!

**Comment by praptisharma28** [comment]
@Rakesh9100 , everything is fine now, have a look!

**Comment by Rakesh9100** [comment]
Looks fine!!

Add a zoom in or pop-in and pop-out animation while opening and closing the instruction box as present on the website now @praptisharma28

**Comment by Rakesh9100** [comment]
Looks fine!!

Add a zoom in or pop-in and pop-out animation while opening and closing all three instruction boxes as present on the website now @praptisharma28

**Comment by Rakesh9100** [comment]
Sure, you can open new issue for this yourself and will assign you if you want to!! @praptisharma28

**Comment by Rakesh9100** [comment]
Good UI of the box, Merged!! 🎉✨

Congrats on getting your PR merged to this repo under IWOC 2.0 🎉🎉 @praptisharma28

**Comment by praptisharma28** [comment]
Thanks a lot @Rakesh9100 , please open the new issue and assign me, I am working on the pop up you want!

**Comment by Rakesh9100** [comment]
It's good to open up the issue yourself if you want to work and I will assign that issue to you @praptisharma28

**Comment by Rakesh9100** [comment]
Sure, go ahead @praptisharma28

**Pull request merged**
