### PR TITLE
Added a Star rating system

### LINKED ISSUE #226: [Feature] Add a Star rating system
### Description

I would like to add a star rating system for the users to rate their experience.
The icon would be present in the footer of the webpage, which upon clicking will navigate to the star rating page.
I am attaching some screenshots for better understanding.

I would like to work on this issue under JWOC.
Thank you 

### Screenshots

image

image

image

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Sneha6003**
# Fixes Issue🛠️

Closes #226 

# Description👨‍💻 

added feedback form.

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added demonstration in the form of GIF/video file
- [X] I am an Open Source Contributor

# Screenshots/GIF📷
image
image
image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
1. Where are the feedbacks getting received, you should implement a script logic such that feedback comes to my email directly!!

2. A form should popup on the screen instead of opening a new feedback page tab which would look quite good @Sneha6003

**Comment by Rakesh9100** [comment]
Are you working @Sneha6003

**Comment by Sneha6003** [comment]
yes im working @Rakesh9100

**Comment by Rakesh9100** [comment]
Update your work on the suggested changes and complete the PR by today @Sneha6003

**Pull request closed without merging**
