### PR TITLE
#33 issue : Removed home icon and added Back icon

### PR DESCRIPTION
**Pull request by AK-shat-JAIN**
# Fixes Issue🛠️

Removed home icon and Added Back icon

# Description👨‍💻 

removed Home icon as of no use on home page and added back icon in food items list page

# Type of change📄

- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

change in 3 files

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added a demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷

image
image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Resolve the conflict by git pull the code or fork and clone again the codebase @AK-shat-JAIN

**Comment by AK-shat-JAIN** [comment]
Hello @Rakesh9100 I don't know how to resolve conflicts 
At my PR there is no merge conflicts can you guide me on how to resolve that?

**Comment by Rakesh9100** [comment]
Sure. Delete your existing fork of this project, then fork again and clone and then again make changes to the new codebase and make a new PR. This happens because a major change is done in the code due to merging of a PR so you have to update that change and then make the new PR.

**Comment by AK-shat-JAIN** [comment]
Sure sr doing this by an hour please merge that one on priority

**Comment by Rakesh9100** [comment]
Will do, surely.

**Comment by AK-shat-JAIN** [comment]
Thank you

**Pull request closed without merging**
