### PR TITLE
feat : Added interactive sounds for better game UX

### LINKED ISSUE #138: Feature: Adding new sound effects for better UX
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

## Addition of new sound effects for better UX @SloP 3.0
Adding new Sound files (mp3/wav or such) to notify gameover, updating the sound effect of clicking the edible, and other such features (like playing a BGM for the game in a loop and others).

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by SoumyadevSaha**
# Fixes Issue🛠️

Closes #138 

# Description👨‍💻 

## Applied Changes 
1. **Added game BGM** : Added 2 game BGMs, one for when the user is playing the game, and another when they are selecting from the menu. (both bgms are in loop, i.e, if reaches end of file, starts from beginning)
2. **Added GameOver music** : Added a gameOver music, which is played when the game gets over.
3. **Smooth transition between music(s)**: When it is gameOver/pause/reload/back to menu/back to game events, the game logic[main.js] is updated such that the transition between 2 musics are handled smoothly.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Tested on local machine, after the changes were made. All plays out smoothly.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls delete every .DS_Store files @SoumyadevSaha

**Comment by SoumyadevSaha** [comment]
> Pls delete every .DS_Store files @SoumyadevSaha

Deleted the .DS_Store files

**Comment by Rakesh9100** [comment]
Amazing work, Really liked the sounds !! Merged @SoumyadevSaha 🎉🥳

**Comment by Rakesh9100** [comment]
give @SoumyadevSaha 150 points

**Comment by SoumyadevSaha** [comment]
> Amazing work, Really liked the sounds !! Merged @SoumyadevSaha 🎉🥳

Thankyou so much 😁

**Pull request merged**
