### PR TITLE
Updated UI

### LINKED ISSUE #13: Design UI of home screen
You can animate the home screen and make better UI (Ex: include animations)

### PR DESCRIPTION
**Pull request by ADITI-2003**
# Fixes Issue🛠️
Closes #13 

# Description👨‍💻 
I have updated the UI keeping in mind the expectations of the mentor regarding linear gradient color.

# Type of change📄
- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅
I have played the game myself and trail was a success.

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷
Screenshot 2023-02-27 at 12 33 54 PM
Screenshot 2023-02-27 at 7 51 03 PM
Screenshot 2023-02-27 at 7 51 15 PM
Screenshot 2023-02-27 at 7 51 27 PM

### CODE REVIEW

**Comment by Rakesh9100** [comment]
You made too simple, fine, but at least change make background color when changed to dark theme. @ADITI-2003

**Comment by Rakesh9100** [comment]
This is dark theme background, right ?

**Comment by ADITI-2003** [comment]
> > You made too simple, fine, but at least change background color when changed to dark theme. @ADITI-2003
> 
> ok @Rakesh9100

I am not able to change for dark mode, sorry

**Comment by ADITI-2003** [comment]
> Owner

**Comment by ADITI-2003** [comment]
> This is dark theme background, right ?

Design option for improvment.

**Comment by Rakesh9100** [comment]
You have to just make different backgrounds for both the themes ? Slightly dark background wrt dark theme and light bg wrt light theme, that's it @ADITI-2003

**Comment by Rakesh9100** [comment]
You have to just make different backgrounds for both the themes . Slightly dark background wrt dark theme and light bg wrt light theme, that's it @ADITI-2003 The previous one you shown is better for light one but it should change when dark theme is toggled

**Comment by ADITI-2003** [comment]
> You have to just make different backgrounds for both the themes ? Slightly dark background wrt dark theme and light bg wrt light theme, that's it @ADITI-2003

Yes understood, I am trying again, actually having some issue with code for dark mode.

**Comment by ADITI-2003** [comment]
> You have to just make different backgrounds for both the themes . Slightly dark background wrt dark theme and light bg wrt light theme, that's it @ADITI-2003 The first starting one you shown is better for light one but it should change when dark theme is toggled

Trying again

**Pull request closed without merging**
