### PR TITLE
Updated home icon

### PR DESCRIPTION
**Pull request by YashBawa**
# Fixes Issue #7 🛠️

# Description👨‍💻 

A home icon is added to the webpage which refreshes the page on being clicked.

# Type of change📄
- [Y] New feature (non-breaking change which adds functionality)

# Checklist✅ 

- [Y] My code follows the style guidelines of this project
- [Y] I have performed a self-review of my own code
- [Y] I have added demonstration in the form of GIF/video file
- [Y] I am an Open Source Contributor

# Screenshots/GIF📷
Home icon on the bottom right refreshes the page on being clicked
image
The button doesn't execute the operation while the game is being played else the fruit count will get logically disturbed it works for all other conditions.

### CODE REVIEW

**Comment by YashBawa** [comment]
@Rakesh9100 please review and verify it.
Thanks!!

**Comment by Rakesh9100** [comment]
Pls show the working in the form of a demonstrating video @YashBawa

**Comment by YashBawa** [comment]
Ok will update by tomorrow night 👍

**Comment by YashBawa** [comment]
@Rakesh9100 video shows how reload button was not working on the second page and the home icon resolved that issue.
[Fri Oct 14 2022 7_00_52 PM.webm](https://user-images.githubusercontent.com/90853282/195859946-c658b647-c7a0-4a63-b27c-fb21985ebf90.webm)

**Comment by Rakesh9100** [comment]
It's good, but why have you deleted the code line for the favicon. Make the favicon appear again. @YashBawa

**Comment by YashBawa** [comment]
@Rakesh9100 updated the code , please check !!
Thanks for the review.☻

**Comment by Rakesh9100** [comment]
Good work !! @YashBawa

**Comment by YashBawa** [comment]
Please merge it under hacktoberfest label . 
Thank you 😊

**Comment by Rakesh9100** [comment]
> Please merge it under hacktoberfest label . Thank you 😊

Already done don't panic 🙃

**Comment by YashBawa** [comment]
@Rakesh9100  Yaa just saw it wasn't visible due to a bad network. 
Thanks btw ♦️ 
Yaa definitely would be happy to work on it, just need a few days after the 19th can work, since am stuck 😢in mid-sem exams, hope you would understand  😄  !

**Comment by Rakesh9100** [comment]
No issues, focus on the exams. Ask anytime for the issue to get assigned if you want to work. @YashBawa

**Comment by YashBawa** [comment]
Yup ok 👍!!

**Pull request merged**
