### PR TITLE
Language Translator

### LINKED ISSUE #119: Language Translator
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Hey @Rakesh9100  , I would like to open this issue under JWOC.

### Screenshots

- User can translate the text into any language with just one click.
- user can select the preferred language from all the possible languages (100+ including hindi) available on Google
- after selecting a specific language, user will be able to :
   - again translate the page by choosing new language
   - showing the original language
   - turn off the translation for that site

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by ritika728**
# Fixes Issue🛠️

Closes #119. Kindly review @Rakesh9100 

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

https://user-images.githubusercontent.com/91181981/224575529-0d4d3179-6205-4548-8036-3e094e0132aa.mp4

### CODE REVIEW

**Comment by Rakesh9100** [comment]
After translating to any language, the hover effect on every button is not covering them properly, see to this @ritika728

**Comment by ritika728** [comment]
@Rakesh9100 i have made the necessary changes. Please review

**Comment by Rakesh9100** [comment]
Pls check the hover effect on main "Play Game" button. The motion is too fast. Keep it as in every button and as it was before. @ritika728

**Comment by Rakesh9100** [comment]
One main issue happening that if we select any other language, then after choosing any time duration let's say 30sec, then the time indication is showing NaN and not ending the game in any language selected.

image

**Comment by Rakesh9100** [comment]
Status @ritika728

**Pull request closed without merging**
