### PR TITLE
Making a dark theme of the game and enhance the UI #19

### PR DESCRIPTION
**Pull request by kushaljgec2025**
#19 

Fix 1: 
change 1
Changed Ui
fix 2:
change2
Change landing page UI dark theme
fix 3:
change 3
Screen page ui chnaged
fix :4:
change 4
And its dark theme
fix :5
change 5
Changed time and score blocks ui;

fix :6
change 6
add bubble 
fix :7
It was an issue that when we click on the home icon its redirected to GitHub deployed page but its not right way to track bback to the landing page so I fixed this isuue . I have used
location.reload()
to reload that page it comes in the landing page 
chnage 7

### CODE REVIEW

**Comment by kushaljgec2025** [comment]
I have made the all change I mentioned and also fixed a bug and it was a serious bug .mentioned in "fix:7 ". Please check it out and merge it if there is no problem if any changes are required tell me. and as I solved an extra bug that was serious also I request you to make ta tag hard.

**Comment by kushaljgec2025** [comment]
And there is 3 conflicts and dont know how to resolve them.Is is it any problem?

**Comment by Rakesh9100** [comment]
You will have to resolve the conflict before I merge the PR @kushaljgec2025

**Comment by Rakesh9100** [comment]
To resolve this you should do git pull to update the codebase since many new changes have been done in the main repo and then make you changes and push. @kushaljgec2025

**Comment by kushaljgec2025** [comment]
Or you can delete your fork and fork again and clone it and then commit and make your PR.
I did this. please check. thank u for helping.

**Pull request closed without merging**
