### PR TITLE
Pause by space key

### LINKED ISSUE #32: Add the feature to pause the game by space bar
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Hi!
myself Kartikey Agarwal JWoC'23 contributor.
i want to work or fix the thing that pause button only works when clicked via mouse but it will be better if player could pause the game by space bar key while playing the game.
i wish to work on this issue.

### Screenshots

_No response_

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by D3vilGhost**
Closes #32 
 
Issues i have worked on are:
1) I have corrected the spelling of guava in index.html
2) added the an event listener which checks if space key is pressed or not , if space key is pressed and game is running it will pause the game and again pressing the space key will resume the game.
3) to make sure that if user press the space key at home screen then pause menu doesn't open up , i have initialized "isRunning" variable by -1 thus event listener will only work when isRunning is either 1(playing) or 0(paused) and not on home screen.

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls attach the changes recording @D3vilGhost

**Comment by Rakesh9100** [comment]
Nice!! Congrats on getting your PR merged 🎉 @D3vilGhost

**Comment by D3vilGhost** [comment]
Here's the video on the issue i have worked on ..
[https://drive.google.com/drive/folders/1zpypTMVCz7i1mcqPSORHXYjXo8LvJ0Wz](https://drive.google.com/drive/folders/1zpypTMVCz7i1mcqPSORHXYjXo8LvJ0Wz)

 This PR was made by @D3vilGhost under JWoC'23 and it solves & closes the issue #32 .

**Comment by D3vilGhost** [comment]
Here's the video preview:

https://user-images.githubusercontent.com/118762881/219658069-daeaa8dd-ede4-4009-9806-fbaaf6731a77.mp4

**Comment by Rakesh9100** [comment]
Nice!! Congrats on getting your PR merged 🎉 @D3vilGhost

**Comment by Rakesh9100** [comment]
Nice!! Congrats on getting your PR merged 🎉 @D3vilGhost

**Pull request merged**
