### PR TITLE
Added Error Page

### LINKED ISSUE #122: Create Error Page
### Prerequisites

- [X] I am an Open Source Contributor
- [x] I checked to make sure that this issue has not already been filed

### Description

Want to create a 404 responsive error page for the website.

### Screenshots

I want to work on this issue under JWOC

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by TuhinBanerjee31**
# Fixes Issue🛠️

Closes #122 

Created an Error page with a responsive design. Added js for loading effect. Also had floating graphics on the right side. So it would be great if u feel like giving diff level.

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷

https://user-images.githubusercontent.com/76838565/225083170-f4ca6cac-297e-4c79-8f7e-5f792efa63f5.mp4

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Make it proper responsive. Keep the height 626px and change the screen width and check. The footer is not visible for devices less than 1024 px. @TuhinBanerjee31 

image

image

**Comment by TuhinBanerjee31** [comment]
Okay, will fix the responsiveness issue. And the method of connecting the Error page doesn't functions on localhost. it needs to get hosted somewhere like GitHub pages and then only it functions. @Rakesh9100

**Comment by Rakesh9100** [comment]
Yes, I was a bit mistaken and so deleted that comment. Don't worry @TuhinBanerjee31

**Comment by TuhinBanerjee31** [comment]
Screenshot (75)
Screenshot (74)
Screenshot (73)



Fixed Responsiveness issues for all desktop, tab, and mobile views. @Rakesh9100

**Pull request merged**
