### PR TITLE
Instruction box made responsive

### LINKED ISSUE #210: [Bug] Responsiveness of the instruction box
### Description

The lets get started button is not shown properly and it is not clear from the view of the screen shot.

### Screenshots

Screenshot from 2024-01-15 22-26-50

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Click-The-Edible-Game/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Lavanya-Sathya**
# Fixes Issue🛠️

Closes #210 

# Description👨‍💻 

 Instruction box is made responsive for all the screen size

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)

# How this has been tested✅

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷
https://z55ui8khzf.vmaker.com/record/x7BYNf5wtPS0sHEd

### CODE REVIEW

**Comment by Rakesh9100** [comment]
image

Why the instruction box of this screen is changed and also of the playing screen, do fix pls @Lavanya-Sathya

**Comment by Lavanya-Sathya** [comment]
Hey @Rakesh9100, I have fixed the issue. Please review

**Comment by Rakesh9100** [comment]
image
### This is the current website where instruction box is not overlapping with footer and navbar.

image
### But after your changes, the box is overlapping, so pls fix @Lavanya-Sathya

**Comment by Rakesh9100** [comment]
Good, Merged!! Congrats on getting your PR merged to this repo under JWOC 🎉🎉 @Lavanya-Sathya

**Pull request merged**
